name: kg-mcqa
channels:
  - defaults
  - conda-forge
dependencies:
  # General
  - python==3.11  # for PyTorch stability
  - matplotlib
  - pandas
  - nltk
  - pyvis
  - pip
  # Machine Learning
  - pytorch
  - transformers==4.44
  - sentence-transformers
  - accelerate
  # Development
  - cython # for building kgraph library
  - pytest
  - streamlit
  - pip:
    - ./kgraph
    - wikipedia
    # Documentation
    - sphinx
    - myst-parser
    - sphinx_rtd_theme
    - sphinx-press-theme
