[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kgraph"
version = "0.1.1"
description = "A Python library for knowledge graph construction and relation extraction from text."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Naoki Shimoda", email = "naoki.shimoda@outlook.jp" }
]
dependencies = [
    "transformers",
    "sentence-transformers",
    "torch",
    "numpy",
    "pandas",
    "networkx",
    "pytest>=8.3",
]

[project.optional-dependencies]
dev = ["black", "isort", "flake8", "mypy"]

[tool.setuptools.packages.find]
where = ["."]
